---
- pip:
    name: packet-python

- include_vars: packet_config.yaml
- include_vars: packet_config_secret.yaml
- packet_sshkey:
    key_file: "{{packet_ssh_key}}"
    label: "OKD KubeVirt Demo Key"
    auth_token: "{{packet_auth_token}}"

- packet_device:
    project_id: "{{packet_project_id}}"
    auth_token: "{{packet_auth_token}}"
    hostnames: "{{packet_hostname}}"
    operating_system: "{{packet_os}}"
    plan: "{{packet_plan}}"
    facility: "{{packet_facility}}"
    wait_for_public_IPv: 4
  when: not ansible_check_mode
