---
- name: Download virtctl client
  get_url:
    url: "https://github.com/kubevirt/kubevirt/releases/download/v0.10.0/virtctl-v0.10.0-linux-amd64"
    dest: "/root/"

- name: Move virtctl client into path
  shell: "mv /root/virtctl-v0.10.0-linux-amd64 /usr/local/bin/virtctl"
  args:
    creates: "/usr/bin/virtctl"
    removes: "/root/virtctl-v0.10.0-linux-amd64"

- name: Mark virtctl executable
  file:
    path: "/usr/local/bin/virtctl"
    mode: "0777"
