---
- name: Download oc client
  get_url:
    url: "https://github.com/openshift/origin/releases/download/v3.11.0/openshift-origin-client-tools-v3.11.0-0cbc58b-linux-64bit.tar.gz"
    dest: "/root/"

- name: Extract oc client
  unarchive:
    src: "/root/openshift-origin-client-tools-v3.11.0-0cbc58b-linux-64bit.tar.gz"
    remote_src: "yes"
    dest: "/root/"

- name: Move oc client to path
  command: "mv /root/openshift-origin-client-tools-v3.11.0-0cbc58b-linux-64bit/oc /usr/local/bin/oc"
  args:
    creates: "/usr/local/bin/oc"
    removes: "/root/openshift-origin-client-tools-v3.11.0-0cbc58b-linux-64bit/oc"

- name: Move kubectl client to path
  command: "mv /root/openshift-origin-client-tools-v3.11.0-0cbc58b-linux-64bit/kubectl /usr/local/bin/kubectl"
  args:
    creates: "/usr/local/bin/kubectl"
    removes: "/root/openshift-origin-client-tools-v3.11.0-0cbc58b-linux-64bit/kubectl"

- name: Mark oc client executable
  file:
    path: "/usr/local/bin/oc"
    mode: "0777"

- name: Mark kubectl client executable
  file:
    path: "/usr/local/bin/oc"
    mode: "0777"

- name: Install Docker
  package:
    name: "docker"
    state: "latest"

- name: Configure for insecure registry
  copy:
    content: "{ \"insecure-registries\": [ \"172.30.0.0/16\" ] }"
    dest: "/etc/docker/daemon.json"

- name: Start Docker
  service:
    name: "docker"
    state: "started"
    enabled: "yes"

- name: Start OpenShift
  shell: "oc cluster up"

- name: Set access control for local PVs
  find:
    paths: "/root/openshift.local.clusterup/openshift.local.pv/"
    patterns: "pv*"
  register: "files_setfacl"

- name: Ansible remove file glob
  acl:
    path: "{{ item.path }}"
    etype: "user"
    entity: "107"
    permissions: "rwx"
    state: "present"
  with_items: "{{ files_setfacl.files }}"
